### YamlMime:UniversalReference
items:
  - uid: excel.Excel.SettingsChangedEventArgs
    summary: |-
      Provides information about the setting that raised the SettingsChanged event 

       \[Api set: ExcelApi 1.4\]
    name: Excel.SettingsChangedEventArgs
    fullName: excel.Excel.SettingsChangedEventArgs
    langs:
      - typeScript
    type: interface
    package: excel
    children:
      - excel.Excel.SettingsChangedEventArgs.settings
  - uid: excel.Excel.SettingsChangedEventArgs.settings
    summary: |-
      Gets the Setting object that represents the binding that raised the SettingsChanged event 

       \[Api set: ExcelApi 1.4\]
    name: settings
    fullName: excel.Excel.SettingsChangedEventArgs.settings
    langs:
      - typeScript
    type: property
    syntax:
      content: 'settings: Excel.SettingCollection;'
      return:
        type:
          - Excel.SettingCollection
